"""
AARKAA – Verification Agent
Provides verification passes for critical domains (coding, debugging, finance, trading).
"""
from __future__ import annotations

import logging
import os
import time
from typing import Dict, Any, List, Optional
from modules import aarkaa_engine

logger = logging.getLogger(__name__)

SYSTEM_VERIFIER_PROMPT = """You are the AARKAA Verifier Agent. Your sole responsibility is to audit, verify, and correct responses generated by other agents or models. You must ensure maximum correctness, safety, logical soundness, and formatting compliance.

Perform an in-depth audit covering the following verification rules:
1. Logical & Math Verification: Verify that all calculations, formulas, values, or statistics mentioned are mathematically correct. If there is a calculation error, correct it using precise logic.
16: 2. Coding/Debugging Audit: Check that code blocks are properly formatted and closed, contain valid syntax, do not contain placeholders (like '// insert code here'), and use correct parameters. For compiled languages (such as C/C++), strictly verify pointer arithmetic, struct member definitions, type safety, memory allocations (e.g. check malloc returns, buffer sizes, string terminations), and B+ tree node splits logic. Correct any syntax errors directly.
3. Formatting & Markdown Compliance: Verify that all lists, tables, code blocks, bold/italic symbols, and math equations (LaTeX $...$ or $$...$$) are perfectly formatted. Fix any broken tags or tables.
4. Completeness check: Ensure there are no unfinished sentences, placeholders, or meta-comments.
5. Domain-Specific Safeguards:
   - For financial, trading, or investment queries: Confirm that relevant formulas are explained and ensure that a clear disclaimer (e.g., "Disclaimer: This is for educational purposes and does not constitute financial advice.") is present.
   - For medical or health queries: Ensure a standard health disclaimer is included.
6. Language Consistency: The final output must be completely in the same language as the user's original query.
7. Entity & Location Verification: Audit and cross-reference mentioned entities, institutions, or landmarks. Ensure they actually belong to the user's requested location, city, or region (e.g., reject or remove Kerala-based institutions if the query requested Mangalore institutions).
8. Category & Source Validation: Verify that listed entities belong strictly to the requested category (do not mix general colleges, coaching classes, or polytechnics if the request asks specifically for "engineering colleges"). Ensure that any statistics, metrics, or counts are explicitly attributed to their exact retrieved sources (e.g., "According to ZoomColleges...", "Wikipedia reports..."). Do NOT alter or upscale source provenance (do not claim a count is 'according to AICTE' unless the AICTE database itself was directly retrieved and verified in the search results). Penalize and flag numbers from weak directory portals (like Justdial) unless clearly labeled as unverified.
9. Statistical and Census Count Accuracy: For any query requesting statistics, census numbers, or counts (e.g., number of colleges, population, startup counts):
    - Frame the count precisely by explaining that the exact number depends on the definition used (e.g., AICTE-approved institutions, state/regional counseling-participating colleges, affiliated colleges, deemed universities, etc.).
    - Do not state a single generic unsupported number without stating the exact scope, source, and context.
    - Compare counts across all retrieved sources to identify consensus and conflicts. Present any variance transparently (e.g., noting that one portal reports 16 while another lists 18) and explain the potential reasons.
    - Separate distinct categories carefully: do not group national-level institutions (like IITs or NITs) with general state-affiliated or private engineering colleges. Be precise about their counts.
    - For regional engineering college counts, ensure the response frames the count professionally: explain that the exact number depends on the definition used (AICTE-approved, counseling-participating, or deemed universities), present the specific counts and variance found across the retrieved sources (e.g. ZoomColleges reporting 16 and Propelld listing over 18 for Mangalore) rather than using generic templates or fabricating estimates, and explicitly direct the user to the latest official AICTE-approved institution list or regional Directorate of Technical Education records for an authoritative count.
10. Definition Validation & Semantic Grounding (CRITICAL):
    If Retrieved Evidence is provided:
    - Identify every count, statistic, metric, or number mentioned in the proposed response.
    - Locate the source sentence or context for each number in the provided Retrieved Evidence.
    - Validate the semantic definition: check if the concept being counted in the source EXACTLY matches the concept or scope requested in the user's query.
    - Carefully distinguish between a ranked or curated subset (e.g., '196 top engineering colleges ranked by Careers360') and the absolute statewide or regional total (e.g., 'around 1320 colleges in TN overall').
    - Never present a subset count as the absolute total. If the user asks for the total count, and the evidence only lists a ranked subset count, do NOT state the subset count as the total. Instead, rewrite the response to clarify the distinction, present the subset count as what it is (e.g. '196 ranked colleges'), present the true total if mentioned in the evidence (e.g. 'around 1320 overall colleges'), and transparently explain the definition variance or ambiguity.

11. Self-Evaluation & Completeness Check (CRITICAL):
    - Is the answer complete and direct? Ensure the response directly answers the core user request first.
    - Does it follow the required visual diagram criteria? If the query is about system design, request flow, pipelines, or database operations, check if the response includes a box-drawing Unicode diagram at the top. If missing, generate and insert one.
    - Are there any unsupported claims? Audit the response against the Retrieved Evidence. If the model makes claims, numbers, or facts not present in the evidence or known database, correct them.
    - Is anything important missing? Check if the response omitted any sub-questions, edge cases, or required sections (like advantages/disadvantages). If missing, expand and add them.
12. Structural Compliance & Adaptive Templates (CRITICAL):
    - Verify that the response contains the exact required headers (e.g. ### 1. Requirements, ### 2. Capacity Estimation...) matching the query domain and answer type.
    - If any section is missing or empty, rewrite the response to fully implement that section in depth.
    - Do NOT output placeholder comments like '// insert code here' or 'Under construction'. All content must be complete.

If the proposed response is completely correct, safe, and formatted, output it exactly as-is.
If any corrections are needed, rewrite the response to fix the errors, fill missing gaps, and output the corrected version directly.
CRITICAL: Do NOT output any meta-conversation, explanations, or preambles (e.g. do NOT write "Here is the verified response", "Verification passed:", "Changes made:"). Just output the final validated response text directly."""


def _is_corrupted_diagram(text: str) -> bool:
    """Detect if the text contains a corrupted or misaligned box-drawing layout."""
    import re
    # Look for blocks with high density of drawing characters
    drawing_chars = set("│┌┐└┘├┤┬┴┼─▶▼▲")
    lines = text.split("\n")
    for line in lines:
        draw_count = sum(1 for c in line if c in drawing_chars)
        # If a single line has overlapping/clashing connectors (e.g. multiple vertical lines crossing words)
        if draw_count > 3:
            # Check for corrupted combinations like ───┼ or ├──│ or overlapping arrows
            if re.search(r"├──│|───┼|──┬──┘|▶├|├──▶", line):
                return True
            # Also check if it mixes characters and runs together without spacing
            if re.search(r"[a-zA-Z]{3,}[│┌┐└┘├┤┬┴┼─]{2,}", line):
                return True
    return False


def _strip_react_format(text: str) -> str:
    """Strip ReAct agent format (Thought/Action/Observation) from model output.
    
    When the model hallucinates a ReAct loop, it outputs:
        Thought: ...
        Action: FileEditTool
        Action Input: {"content": "<actual code>", ...}
        Observation: ...
    We extract only the clean content and discard the scaffolding.
    """
    import re
    import json

    stripped = text.strip()

    # If no ReAct markers, return as-is
    if not re.search(r'^(Thought:|Action:|Observation:)', stripped, re.MULTILINE):
        return stripped

    logger.info("Verifier: Detected ReAct-format output — stripping scaffolding")

    # Strategy 1: Extract 'content' field from Action Input JSON blocks
    content_blocks = []
    for m in re.finditer(r'Action Input:\s*(\{.*?\})', stripped, re.DOTALL):
        try:
            payload = json.loads(m.group(1))
            if 'content' in payload and payload['content'].strip():
                content_blocks.append(payload['content'].strip())
        except (json.JSONDecodeError, KeyError):
            pass

    if content_blocks:
        return '\n\n'.join(content_blocks)

    # Strategy 2: Collect all Observation: sections as they are the final outputs
    observations = re.findall(r'Observation:\s*(.*?)(?=(?:Thought:|Action:|Observation:|$))', stripped, re.DOTALL)
    if observations:
        clean = [o.strip() for o in observations if o.strip()]
        if clean:
            return '\n\n'.join(clean)

    # Strategy 3: Strip all Thought:/Action:/Observation: lines and return the remainder
    lines = stripped.split('\n')
    clean_lines = []
    skip = False
    for line in lines:
        if re.match(r'^(Thought:|Action:|Action Input:|Observation:)', line.strip()):
            skip = True
            continue
        if skip and line.strip() == '':
            skip = False
        if not skip:
            clean_lines.append(line)
    
    result = '\n'.join(clean_lines).strip()
    return result if result else text


def _repair_system_diagram(query: str, response: str) -> str:
    """Run a highly targeted prompt to rewrite only the broken diagram into a clean Unicode flow."""
    logger.info("Verifier: Intercepted corrupted diagram — executing targeted visual repair pass")
    repair_prompt = (
        "<|im_start|>system\n"
        "You are a master systems architect specializing in drawing clean request flow diagrams.\n"
        "Your task is to take the user's architectural concept and draw a clean, logically aligned "
        "vertical text flow diagram using box-drawing characters (│, ▼, ├──, └──, ─►).\n"
        "Ensure there are NO clashing lines, overlapping boxes, or corrupted connector strings.\n"
        "Return ONLY the clean diagram inside a ```text code block. Do NOT write any introduction or explanation.<|im_end|>\n"
        f"<|im_start|>user\n"
        f"Draw a clean vertical request flow diagram for: {query}\n\n"
        "Example of correct format:\n"
        "```text\n"
        "Client\n"
        "  │\n"
        "  ▼\n"
        "Gateway\n"
        "  │\n"
        "  ├── Cache Hit ─► Return\n"
        "  │\n"
        "  └── Cache Miss\n"
        "        │\n"
        "        ▼\n"
        "     Database\n"
        "```<|im_end|>\n"
        "<|im_start|>assistant\n"
    )
    try:
        clean_diag = aarkaa_engine._generate(repair_prompt, max_new_tokens=1024, temperature=0.1)
        clean_diag = clean_diag.strip()
        
        if "```" in clean_diag:
            import re
            # 1. Strip any fenced code block diagrams
            cleaned = re.sub(r"```text.*?```", "", response, flags=re.DOTALL).strip()
            cleaned = re.sub(r"```.*?```", "", cleaned, flags=re.DOTALL).strip()
            
            # 2. Strip any remaining lines in the text containing raw box-drawing characters
            drawing_chars = set("│┌┐└┘├┤┬┴┼─▶▼▲")
            filtered_lines = []
            for line in cleaned.split("\n"):
                draw_count = sum(1 for c in line if c in drawing_chars)
                # Skip any lines that are clearly part of the raw unfenced diagram
                if draw_count > 2:
                    continue
                filtered_lines.append(line)
            
            cleaned_response = "\n".join(filtered_lines).strip()
            return clean_diag + "\n\n" + cleaned_response
    except Exception as exc:
        logger.error("Failed to run targeted diagram repair: %s", exc)
    return response


def verify_response(query: str, response: str, evidence: str = None) -> str:
    """Audits and refines response to ensure high quality and domain safety compliance."""
    # First, run the visual check to intercept and repair corrupted diagrams
    if _is_corrupted_diagram(response):
        response = _repair_system_diagram(query, response)

    from modules.aarkaa_engine import _classify_and_plan
    plan = _classify_and_plan(query)
    
    rules = [
        "1. Logical & Math Verification: Verify that all calculations, formulas, values, or statistics mentioned are mathematically correct. If there is a calculation error, correct it using precise logic.",
        "2. Coding/Debugging Audit: Check that code blocks are properly formatted and closed, contain valid syntax, do not contain placeholders (like '// insert code here'), and use correct parameters. For compiled languages (such as C/C++), strictly verify pointer arithmetic, struct member definitions, type safety, memory allocations (e.g. check malloc returns, buffer sizes, string terminations), and B+ tree node splits logic. Correct any syntax errors directly.",
        "3. Formatting & Markdown Compliance: Verify that all lists, tables, code blocks, bold/italic symbols, and math equations (LaTeX $...$ or $$...$$) are perfectly formatted. Fix any broken tags or tables.",
        "4. Completeness check: Ensure there are no unfinished sentences, placeholders, or meta-comments.",
    ]
    
    if plan["domain"] == "finance":
        # Skip general finance guidelines for concise real-time stock/crypto tickers queries
        is_live_finance = evidence and "[Finance Data]" in evidence
        if not is_live_finance:
            rules.append("5. Domain-Specific Safeguards: Confirm that relevant formulas are explained and ensure that a clear disclaimer (e.g., 'Disclaimer: This is for educational purposes and does not constitute financial advice.') is present.")
    elif plan["domain"] == "health":
        rules.append("5. Domain-Specific Safeguards: Ensure a standard health disclaimer is included.")
        
    rules.extend([
        "6. Language Consistency: The final output must be completely in the same language as the user's original query.",
    ])
    
    # Avoid forcing rigid templates for concise live finance tickers queries
    is_live_finance = evidence and "[Finance Data]" in evidence
    if not is_live_finance:
        rules.append("7. Structural Compliance & Adaptive Templates (CRITICAL): Verify that the response contains the exact required headers matching the query domain and answer type. If any section is missing or empty, rewrite the response to fully implement that section in depth. Do NOT output placeholder comments.")
    
    # Integrate dynamic CVR pipeline checks if the domain is coding
    if plan["domain"] == "coding":
        try:
            from modules.cvr_pipeline import StaticAnalyzer, SecurityScanner, PerformanceAnalyzer, CandidateTournament, TrajectoryLogger, DynamicPlanner
            from modules.repo_indexer import WorkspaceSnapshot, RepoGraphStore
            from modules.repair_agents import ChainedRepairController, RepairConfidenceScorer
            import re
            
            # Find python code blocks inside the response
            code_blocks = re.findall(r"```python\s*(.*?)\s*```", response, re.DOTALL)
            if code_blocks:
                logger.info("CVR Pipeline: Analyzing %d python code blocks", len(code_blocks))
                cvr_plan = DynamicPlanner.plan_complexity(query)
                
                # Perform transactional workspace snapshot checkpoint isolation
                snapshot_id = f"snap_verifier_{int(time.time())}"
                target_files = ["cvr_runner_tmp.py"] # Track runner runs
                WorkspaceSnapshot.create_snapshot(snapshot_id, target_files)
                
                errors = []
                repaired_blocks = []
                for idx, block in enumerate(code_blocks):
                    syntax = StaticAnalyzer.verify_syntax(block)
                    if not syntax["valid"] or SecurityScanner.scan(block):
                        # Trigger chained repair flow
                        logger.info("CVR: Broken logic/security signature caught. Triggering ChainedRepairController.")
                        repair_res = ChainedRepairController.attempt_chained_repair(
                            query, block, "assert True # basic test", max_iterations=2
                        )
                        if repair_res["success"]:
                            repaired_blocks.append(repair_res["repaired_code"])
                        else:
                            repaired_blocks.append(block)
                            errors.append(f"Block {idx} failed repair flow: {repair_res['history']}")
                    else:
                        repaired_blocks.append(block)
                            
                # Restore original file modifications if any validations fail
                if errors:
                    logger.warning("CVR: Validations failed. Rolling back workspace snapshots.")
                    WorkspaceSnapshot.restore_snapshot(snapshot_id)
                else:
                    WorkspaceSnapshot.discard_snapshot(snapshot_id)
                    # Apply repaired code blocks back to response text
                    if repaired_blocks:
                        for orig_block, rep_block in zip(code_blocks, repaired_blocks):
                            response = response.replace(orig_block, rep_block)
                            
                success = len(errors) == 0
                log_str = "\n".join(errors) if errors else "Passed CVR Pipeline checks successfully."
                
                # Pick first code block for trajectory log representation
                repr_code = code_blocks[0] if code_blocks else ""
                TrajectoryLogger.log_trajectory(query, repr_code, success, 100.0 if success else 40.0, log_str)
                logger.info("CVR Pipeline Result logged. Success: %s", success)
        except Exception as cvr_err:
            logger.error("Failed executing verifier CVR pipeline verification: %s", cvr_err)


    system_verifier_prompt = (
        "You are the AARKAA Verifier Agent. Your sole responsibility is to audit, verify, and correct responses generated by other agents or models. You must ensure maximum correctness, safety, logical soundness, and formatting compliance.\n\n"
        "Perform an in-depth audit covering the following verification rules:\n"
        + "\n".join(rules)
        + "\n8. Security Enforcement: Ensure that Python subprocess runs do NOT use shell=True and list arguments are strictly used instead to avoid command injection vulnerabilities. If shell=True is found, replace it with list-based arguments."
        + "\n\nIf the proposed response is completely correct, safe, and formatted, output it exactly as-is.\n"
        "If any corrections are needed, rewrite the response to fix the errors, fill missing gaps, and output the corrected version directly.\n"
        "CRITICAL: Do NOT output any meta-conversation, explanations, or preambles (e.g. do NOT write 'Here is the verified response', 'Verification passed:', 'Changes made:'). Just output the final validated response text directly."
    )


    user_prompt = ""
    if evidence:
        user_prompt += f"Retrieved Evidence:\n{evidence}\n\n"
    
    user_prompt += (
        f"Original User Request: {query}\n\n"
        f"Proposed Response to Verify:\n{response}"
    )
    # If CVR pipeline did repairs, return response directly to avoid stub overrides
    if plan["domain"] == "coding" and 'repaired_blocks' in locals() and repaired_blocks:
        return response

    formatted_prompt = aarkaa_engine._build_chatml(system_verifier_prompt, user_prompt)
    try:
        verified = aarkaa_engine._generate(
            formatted_prompt,
            max_new_tokens=1536,
            temperature=0.1,
            force_general=True
        )
        if verified.strip():
            # Strip any ReAct agent format the model may have hallucinated
            verified = _strip_react_format(verified)
            v = verified.strip()
            if v:
                # Safety guard: only replace if the verified output is at least 50%
                # of the original length. A much shorter output indicates the model
                # truncated or hallucinated rather than auditing the response.
                orig_len = len(response.strip())
                if orig_len > 0 and len(v) < orig_len * 0.5:
                    logger.warning(
                        "Verifier output too short (%d chars vs original %d chars) — "
                        "discarding verifier output to preserve original response.",
                        len(v), orig_len
                    )
                    return response
                if v != response.strip():
                    try:
                        from modules.aarkaa_engine import _last_pipeline_metrics
                        _last_pipeline_metrics["verifier_passed"] = False
                        _last_pipeline_metrics["confidence"] = max(0.1, _last_pipeline_metrics["confidence"] - 0.15)
                    except Exception:
                        pass
                return v
    except Exception as exc:
        logger.error("Verification pass failed: %s. Returning original response.", exc)
    
    return response

