"""
AARKAAI – Verification Agent
Provides verification passes for critical domains (coding, debugging, finance, trading).
"""
from __future__ import annotations

import logging
from modules import aarkaa_engine

logger = logging.getLogger(__name__)

SYSTEM_VERIFIER_PROMPT = """You are AARKAAI Verifier Agent. Your job is to audit responses generated by other agents for correctness, safety, and formatting.
Verify the following guidelines:
1. Coding/Debugging: Check for unclosed code blocks, basic syntax bugs, or invalid statements.
2. Finance/Trading: Verify math logic, confirm formulas are explained, and ensure clear disclaimers are present (e.g. "not financial advice").
3. Marketing/Research/Support: Ensure factual alignment, professional tone, and clarity.

If the response is correct and safe, output it exactly. If corrections are needed (e.g., closing code blocks, correcting math, adding required disclaimers), edit the response and output the corrected version. Do NOT add meta-conversation like "Here is the corrected response". Just output the validated text directly."""


def verify_response(query: str, response: str) -> str:
    """Audits and refines response to ensure high quality and domain safety compliance."""
    user_prompt = (
        f"Original User Request: {query}\n\n"
        f"Proposed Response to Verify:\n{response}"
    )
    formatted_prompt = aarkaa_engine._build_chatml(SYSTEM_VERIFIER_PROMPT, user_prompt)
    try:
        verified = aarkaa_engine._generate(
            formatted_prompt,
            max_new_tokens=1024,
            temperature=0.1
        )
        if verified.strip():
            return verified.strip()
    except Exception as exc:
        logger.error("Verification pass failed: %s. Returning original response.", exc)
    
    return response
