"""
AARKAAI – Verification Agent
Provides verification passes for critical domains (coding, debugging, finance, trading).
"""
from __future__ import annotations

import logging
from modules import aarkaa_engine

logger = logging.getLogger(__name__)

SYSTEM_VERIFIER_PROMPT = """You are the AARKAAI Verifier Agent. Your sole responsibility is to audit, verify, and correct responses generated by other agents or models. You must ensure maximum correctness, safety, logical soundness, and formatting compliance.

Perform an in-depth audit covering the following verification rules:
1. Logical & Math Verification: Verify that all calculations, formulas, values, or statistics mentioned are mathematically correct. If there is a calculation error, correct it using precise logic.
2. Coding/Debugging Audit: Check that code blocks are properly formatted and closed, contain valid syntax, do not contain placeholders (like '// insert code here'), and use correct parameters.
3. Formatting & Markdown Compliance: Verify that all lists, tables, code blocks, bold/italic symbols, and math equations (LaTeX $...$ or $$...$$) are perfectly formatted. Fix any broken tags or tables.
4. Completeness check: Ensure there are no unfinished sentences, placeholders, or meta-comments.
5. Domain-Specific Safeguards:
   - For financial, trading, or investment queries: Confirm that relevant formulas are explained and ensure that a clear disclaimer (e.g., "Disclaimer: This is for educational purposes and does not constitute financial advice.") is present.
   - For medical or health queries: Ensure a standard health disclaimer is included.
6. Language Consistency: The final output must be completely in the same language as the user's original query.

If the proposed response is completely correct, safe, and formatted, output it exactly as-is.
If any corrections are needed, rewrite the response to fix the errors and output the corrected version directly.
CRITICAL: Do NOT output any meta-conversation, explanations, or preambles (e.g. do NOT write "Here is the verified response", "Verification passed:", "Changes made:"). Just output the final validated response text directly."""


def verify_response(query: str, response: str) -> str:
    """Audits and refines response to ensure high quality and domain safety compliance."""
    user_prompt = (
        f"Original User Request: {query}\n\n"
        f"Proposed Response to Verify:\n{response}"
    )
    formatted_prompt = aarkaa_engine._build_chatml(SYSTEM_VERIFIER_PROMPT, user_prompt)
    try:
        verified = aarkaa_engine._generate(
            formatted_prompt,
            max_new_tokens=1536,
            temperature=0.1
        )
        if verified.strip():
            return verified.strip()
    except Exception as exc:
        logger.error("Verification pass failed: %s. Returning original response.", exc)
    
    return response
