"""
agent.py — Agentic Loop for Self-Hosted LLM (Custom HTTP Endpoint)

Instead of Anthropic's API, this calls YOUR LLM endpoint.
Tool calling is done via prompt engineering — the model outputs
JSON tool calls inside <tool_call>...</tool_call> tags, which
we parse and execute ourselves.

Configure your endpoint in .env or environment variables:
    LLM_ENDPOINT=http://localhost:8000/v1/chat
    LLM_API_KEY=optional-if-your-server-needs-it
    LLM_MODEL=your-model-name   (optional)
"""

import os
import re
import json
import requests
from tools import TOOL_DEFINITIONS, execute_tool


# ─── Config ───────────────────────────────────────────────────────────────────

LLM_ENDPOINT = os.environ.get("LLM_ENDPOINT", "http://localhost:8000/v1/chat")
LLM_API_KEY  = os.environ.get("LLM_API_KEY", "")
LLM_MODEL    = os.environ.get("LLM_MODEL", "local-model")


# ─── System prompt with tool instructions ─────────────────────────────────────
# Since we're not using native function calling, we teach the model
# how to call tools via a structured format in the prompt itself.

def build_system_prompt() -> str:
    # Format tool definitions as readable JSON for the model
    tools_json = json.dumps(TOOL_DEFINITIONS, indent=2)

    return f"""You are an expert coding assistant with access to a workspace.
You can interact with the filesystem and run commands using tools.

## Available Tools

{tools_json}

## How to Call a Tool

When you need to use a tool, output ONLY this format — nothing before or after:

<tool_call>
{{
  "name": "tool_name",
  "args": {{
    "param": "value"
  }}
}}
</tool_call>

After the tool result is shown to you, continue your reasoning or call another tool.
When you are fully done and ready to give your final answer, write it as normal text
WITHOUT any <tool_call> tags.

## Rules
- Always read a file before editing it
- Write COMPLETE file contents when using write_file — never partial snippets
- Think step by step for complex tasks
- After writing files, explain what you did and why
- If a command fails, read the error and fix it
"""


# ─── HTTP call to your LLM ────────────────────────────────────────────────────

def call_llm(messages: list[dict], model: str = LLM_MODEL) -> str:
    """
    Send messages to your custom LLM endpoint.
    Returns the model's response text.

    Expects an OpenAI-compatible chat endpoint:
        POST /v1/chat
        Body: { "model": "...", "messages": [...] }
        Response: { "choices": [{ "message": { "content": "..." } }] }

    Edit _parse_response() below if your endpoint uses a different format.
    """
    headers = {"Content-Type": "application/json"}
    if LLM_API_KEY:
        headers["Authorization"] = f"Bearer {LLM_API_KEY}"

    payload = {
        "model": model,
        "messages": messages,
        "temperature": 0.2,      # low temp = more consistent tool calls
        "max_tokens": 4096,
    }

    try:
        response = requests.post(
            LLM_ENDPOINT,
            headers=headers,
            json=payload,
            timeout=120,
        )
        response.raise_for_status()
        data = response.json()
        return _parse_response(data)

    except requests.exceptions.ConnectionError:
        raise RuntimeError(
            f"Could not connect to LLM at {LLM_ENDPOINT}\n"
            f"Make sure your server is running and LLM_ENDPOINT is set correctly."
        )
    except requests.exceptions.HTTPError as e:
        raise RuntimeError(f"LLM returned error: {e}\n{response.text}")


def _parse_response(data: dict) -> str:
    """
    Extract the text from your LLM's response.
    Edit this function if your endpoint returns a different JSON shape.

    Common formats:
        OpenAI-compatible:  data["choices"][0]["message"]["content"]
        Simple:             data["response"]
        Custom:             data["output"]["text"]
    """
    # OpenAI-compatible (most common)
    if "choices" in data:
        return data["choices"][0]["message"]["content"]

    # Simple response field
    if "response" in data:
        return data["response"]

    # Fallback: dump the whole response so you can debug
    return json.dumps(data)


# ─── Tool call parser ─────────────────────────────────────────────────────────

def extract_tool_call(text: str) -> dict | None:
    """
    Look for a <tool_call>...</tool_call> block in the model's output.
    Returns parsed dict or None if no tool call found.
    """
    match = re.search(r"<tool_call>\s*(.*?)\s*</tool_call>", text, re.DOTALL)
    if not match:
        return None

    raw_json = match.group(1).strip()
    # Self-heal double curly braces if generated by the model
    if raw_json.startswith("{{") and raw_json.endswith("}}"):
        raw_json = raw_json[1:-1]

    try:
        return json.loads(raw_json)
    except json.JSONDecodeError as e:
        try:
            import ast
            parsed = ast.literal_eval(raw_json)
            if isinstance(parsed, dict):
                return parsed
        except Exception:
            pass
        print(f"  ⚠️  Could not parse tool call JSON: {e}")
        print(f"  Raw: {raw_json[:200]}")
        return None


# ─── The Agent ────────────────────────────────────────────────────────────────

class CodeAgent:
    def __init__(self, model: str = "local-model", max_iterations: int = 20):
        self.model = model
        self.max_iterations = max_iterations
        self.system_prompt = build_system_prompt()
        self.history = []   # conversation history

    def chat(self, user_message: str) -> str:
        """
        Send a message and run the agentic loop until final response.
        Returns the final text.
        """
        self.history.append({"role": "user", "content": user_message})

        for iteration in range(self.max_iterations):

            # Build full messages: system + history
            messages = [
                {"role": "system", "content": self.system_prompt},
                *self.history,
            ]

            # Call the LLM
            response_text = call_llm(messages, model=self.model)

            # Check if the model wants to call a tool
            tool_call = extract_tool_call(response_text)

            if tool_call:
                tool_name = tool_call.get("name", "")
                tool_args = tool_call.get("args", {})

                print(f"  🔧 {tool_name}({_fmt_args(tool_args)})")

                # Execute the tool
                result = execute_tool(tool_name, tool_args)

                print(f"     → {result[:120]}{'...' if len(result) > 120 else ''}")

                # Add assistant's tool call + result to history
                self.history.append({"role": "assistant", "content": response_text})
                self.history.append({
                    "role": "user",
                    "content": f"<tool_result>\n{result}\n</tool_result>"
                })

            else:
                # No tool call — this is the final response
                self.history.append({"role": "assistant", "content": response_text})
                return response_text

        return "Error: reached max iterations without a final response."

    def reset(self):
        """Clear conversation history."""
        self.history = []
        print("🔄 Conversation reset.")


# ─── Helper ───────────────────────────────────────────────────────────────────

def _fmt_args(args: dict) -> str:
    parts = []
    for k, v in args.items():
        v_str = str(v)
        if len(v_str) > 60:
            v_str = v_str[:60] + "..."
        parts.append(f"{k}={repr(v_str)}")
    return ", ".join(parts)
