from modules.subagents.base import CognitiveSubagent, SubagentResult
import json

class CriticAgent(CognitiveSubagent):
    name: str = 'CriticAgent'
    description: str = 'Output verification and hallucination detection.'
    system_prompt: str = """You are an incredibly strict, objective, and analytical verifier of information.
Your task is to analyze answers generated by other agents and verify them against provided tool data to detect hallucinations or factual errors.

Instructions:
1. Check all factual claims in the answer against the provided tool data.
2. Flag any numbers, statistics, or facts not supported by the tool data as hallucinations.
3. Detect logical inconsistencies within the answer.
4. Rate overall quality on a 1-10 scale.
5. You MUST output ONLY valid JSON in the following format:
{"score": N, "issues": ["issue 1", "issue 2"], "verified": true/false, "corrected_answer": "corrected text here" or null}"""
    allowed_tools: list = []
    max_tokens: int = 1024
    temperature: float = 0.0

    def _execute(self, query: str, context: dict) -> str:
        answer_to_verify = context.get('answer_to_verify', '')
        tool_data = context.get('tool_data', '')
        
        user_prompt = f"Verify the following answer.\n\nAnswer to verify: {answer_to_verify}\n\nTool data: {tool_data}\n\nOutput only JSON as instructed."
        
        output = self._invoke_model(self.system_prompt, user_prompt)
        
        try:
            # Try to strip any markdown code blocks if the model outputs them
            cleaned_output = output.strip()
            if cleaned_output.startswith("```json"):
                cleaned_output = cleaned_output[7:-3].strip()
            elif cleaned_output.startswith("```"):
                cleaned_output = cleaned_output[3:-3].strip()
                
            result = json.loads(cleaned_output)
            score = result.get('score', 0)
            
            if '_metadata' not in context:
                context['_metadata'] = {}
            context['_metadata']['critic_score'] = score
            
            if score >= 7:
                return answer_to_verify
            else:
                corrected = result.get('corrected_answer')
                if corrected:
                    return corrected
                return str(result)
        except json.JSONDecodeError:
            return f"Critic failed to output valid JSON. Output was: {output}"

    def _estimate_confidence(self, output: str, context: dict) -> float:
        score = context.get('_metadata', {}).get('critic_score', 5)
        return float(score) / 10.0
